# Generated by Django 4.2.7 on 2025-08-10 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='كود المنتج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, unique=True, verbose_name='كود المنتج')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('date_produced', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإنتاج')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='صورة المنتج')),
                ('quality_status', models.CharField(choices=[('good', 'جيد'), ('average', 'مقبول'), ('rejected', 'مرفوض')], default='good', max_length=10, verbose_name='حالة الجودة')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء (اختياري)')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='product_qrcodes/', verbose_name='QR كود')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_products', to='inventory.inventoryitem', verbose_name='الصنف المرتبط')),
            ],
            options={
                'verbose_name': 'المنتج النهائي',
                'verbose_name_plural': 'المنتجات النهائية',
                'ordering': ['-date_produced'],
            },
        ),
    ]
