# Generated by Django 4.2.7 on 2025-08-23 04:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='خصائص/سمات (JSON)'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='batch_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='رقم التشغيل/الدفعة'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='location_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='موقع التخزين (رمز)'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='lot',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='LOT'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات داخلية'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='خصائص/سمات (JSON)'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='الباركود/GTIN'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التكلفة التقديرية'),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة (ISO4217)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='صورة المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='product_qrcodes/', verbose_name='QR كود'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, verbose_name='Slug (اختياري)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الضريبة %'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='pcs', max_length=32, verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddIndex(
            model_name='finishedproduct',
            index=models.Index(fields=['product_code'], name='products_fi_product_5fc40e_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproduct',
            index=models.Index(fields=['date_produced'], name='products_fi_date_pr_05f675_idx'),
        ),
        migrations.AddIndex(
            model_name='finishedproduct',
            index=models.Index(fields=['quality_status'], name='products_fi_quality_7465f9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
    ]
