# Generated by Django 4.2.7 on 2025-08-10 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('employees', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الفاتورة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('vodafone_cash', 'فودافون كاش'), ('instapay', 'إنستاباي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك'), ('card', 'بطاقة ائتمان'), ('valu', 'ValU'), ('paypal', 'PayPal'), ('postpaid', 'دفع لاحق')], max_length=30, verbose_name='طريقة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('accounting_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الحساب المحاسبي')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='العميل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='أنشأ بواسطة')),
            ],
            options={
                'verbose_name': 'فاتورة بيع',
                'verbose_name_plural': 'فواتير البيع',
            },
        ),
        migrations.CreateModel(
            name='SmartSalesSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_action', models.TextField(verbose_name='الاقتراح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاقتراح')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'اقتراح مبيعات ذكي',
                'verbose_name_plural': 'اقتراحات المبيعات الذكية',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الخصم')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleinvoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفاتورة',
            },
        ),
        migrations.CreateModel(
            name='ProductSalesAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('total_sold', models.PositiveIntegerField(default=0, verbose_name='إجمالي المبيعات')),
                ('alerts', models.TextField(blank=True, null=True, verbose_name='تنبيهات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تحليل مبيعات المنتج',
                'verbose_name_plural': 'تحليلات مبيعات المنتجات',
            },
        ),
        migrations.CreateModel(
            name='ClientPointsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='النقاط')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='العميل')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.saleinvoice', verbose_name='مصدر النقاط')),
            ],
            options={
                'verbose_name': 'سجل نقاط العميل',
                'verbose_name_plural': 'سجلات نقاط العملاء',
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='آخر شراء')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الشراء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'نشاط العميل',
                'verbose_name_plural': 'تحليل نشاط العملاء',
            },
        ),
        migrations.CreateModel(
            name='SalesPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('sales_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي المبيعات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'أداء مبيعات',
                'verbose_name_plural': 'أداء المبيعات',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
