# Generated by Django 4.2.7 on 2025-08-23 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0002_lifecyclestage_product_productlifecycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='BOM-1', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BomLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('uom', models.CharField(default='pcs', max_length=32)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('operation', models.CharField(blank=True, max_length=120, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('change_type', models.CharField(choices=[('design', 'تصميم'), ('material', 'خامة'), ('process', 'عملية تصنيع'), ('packaging', 'تعبئة وتغليف'), ('other', 'أخرى')], default='design', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرفوع'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('implemented', 'منفذ'), ('canceled', 'ملغي')], default='draft', max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('implemented_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(default='pcs', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(default='v1.0', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('archived', 'مؤرشف')], default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['product__code', 'version_code'],
            },
        ),
        migrations.AddField(
            model_name='plmdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='plm/docs/'),
        ),
        migrations.DeleteModel(
            name='DocumentReview',
        ),
        migrations.AddField(
            model_name='productversion',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='product_versions', to='plm.plmdocument'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='plm.producttemplate'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['code'], name='plm_product_code_afae26_idx'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['name'], name='plm_product_name_ee83bf_idx'),
        ),
        migrations.AddField(
            model_name='changerequestitem',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_items', to='plm.bom'),
        ),
        migrations.AddField(
            model_name='changerequestitem',
            name='bom_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_items', to='plm.bomline'),
        ),
        migrations.AddField(
            model_name='changerequestitem',
            name='change_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plm.changerequest'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='change_requests', to='plm.plmdocument'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='from_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cr_from', to='plm.productversion'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='plm.producttemplate'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='to_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cr_to', to='plm.productversion'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='plm.bom'),
        ),
        migrations.AddField(
            model_name='bomline',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_component_in_boms', to='plm.producttemplate'),
        ),
        migrations.AddField(
            model_name='bom',
            name='product_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='plm.productversion'),
        ),
        migrations.AlterField(
            model_name='productlifecycle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycles', to='plm.producttemplate'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddIndex(
            model_name='productversion',
            index=models.Index(fields=['version_code'], name='plm_product_version_2dab10_idx'),
        ),
        migrations.AddIndex(
            model_name='productversion',
            index=models.Index(fields=['status'], name='plm_product_status_d6ee67_idx'),
        ),
        migrations.AddIndex(
            model_name='productversion',
            index=models.Index(fields=['is_active'], name='plm_product_is_acti_2136e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productversion',
            unique_together={('product', 'version_code')},
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['number'], name='plm_changer_number_62befd_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status'], name='plm_changer_status_061638_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['change_type'], name='plm_changer_change__56c7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['code'], name='plm_bom_code_f7f702_idx'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['is_active'], name='plm_bom_is_acti_82a9c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('product_version', 'code')},
        ),
    ]
