# Generated by Django 4.2.7 on 2025-08-16 13:29

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('manager', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دور قسم',
                'verbose_name_plural': 'أدوار الأقسام',
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Job Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('salary_type', models.CharField(choices=[('hourly', 'Hourly'), ('piece', 'Piece'), ('fixed', 'Fixed')], max_length=20, verbose_name='Salary Type')),
                ('default_piece_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Default Piece Rate')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hourly Rate')),
                ('default_daily_hours', models.PositiveIntegerField(default=8, verbose_name='Default Daily Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('visible_on_payroll', models.BooleanField(default=True, verbose_name='Visible on Payroll?')),
                ('used_in_sections', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Used in Sections')),
                ('linked_to_production_stage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linked to Production Stage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unit Name')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('unit_type', models.CharField(choices=[('quantity', 'كمية'), ('weight', 'وزن'), ('volume', 'حجم'), ('time', 'وقت'), ('length', 'طول')], default='quantity', max_length=50, verbose_name='Unit Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_bulk_unit', models.BooleanField(default=False, verbose_name='Is Bulk Unit?')),
                ('conversion_factor', models.FloatField(blank=True, null=True, verbose_name='Conversion Factor')),
                ('used_in_models', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Used in Models')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryAccessOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Granted At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Is Revoked?')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='Auto Generated?')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Revoked By')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='SmartAccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف'), ('asset', 'أصل'), ('liability', 'التزام'), ('equity', 'حقوق ملكية')], max_length=20)),
                ('suggested_debit_account', models.CharField(max_length=255)),
                ('suggested_credit_account', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(verbose_name='Justification')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='Status')),
                ('response_reason', models.TextField(blank=True, null=True, verbose_name='Response Reason')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('requested_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Requested Role')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=100, verbose_name='Risk Type')),
                ('threshold_value', models.FloatField(verbose_name='Threshold Value')),
                ('severity_level', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع')], default='medium', max_length=20, verbose_name='Severity Level')),
                ('applies_to_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applies to Section')),
                ('auto_detected_field', models.CharField(blank=True, max_length=100, null=True, verbose_name='Auto Detected Field')),
                ('action_required', models.TextField(blank=True, null=True, verbose_name='Action Required')),
                ('trigger_auto_action', models.BooleanField(default=False, verbose_name='Trigger Auto Action?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_thresholds_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Duration (Minutes)')),
                ('requires_machine', models.BooleanField(default=False, verbose_name='Requires Machine?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stage_types_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('linked_job_titles', models.ManyToManyField(blank=True, related_name='production_stages', to='core.jobtitle', verbose_name='Linked Job Titles')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('can_create', models.BooleanField(default=False, verbose_name='Can Create?')),
                ('can_read', models.BooleanField(default=True, verbose_name='Can Read?')),
                ('can_update', models.BooleanField(default=False, verbose_name='Can Update?')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Can Delete?')),
                ('section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Section')),
                ('override_reason', models.TextField(blank=True, null=True, verbose_name='Override Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_matrices_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role', verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('weight', models.FloatField(default=1.0, verbose_name='Weight')),
                ('criteria_type', models.CharField(choices=[('discipline', 'انضباط'), ('performance', 'أداء'), ('quality', 'جودة'), ('attendance', 'حضور'), ('safety', 'سلامة')], default='performance', max_length=50, verbose_name='Criteria Type')),
                ('applies_to_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Applies to Department')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='Auto Generated?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_criteria_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
