# Generated by Django 4.2.7 on 2025-08-23 21:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_options_finishedproduct_attributes_and_more'),
        ('production', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_code', models.CharField(blank=True, default='', max_length=16, verbose_name='وحدة القياس (رمز)')),
                ('required_qty', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='كمية مطلوبة')),
                ('available_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='متاح')),
                ('reserved_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='محجوز')),
                ('shortage_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='يُحسب = المطلوب − (المتاح − المحجوز) ولا يقل عن صفر.', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='عجز')),
                ('source_location', models.CharField(blank=True, default='', max_length=64, verbose_name='الموقع/المصدر')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.billofmaterials', verbose_name='شجرة مكونات')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_lines', to='products.product', verbose_name='مادة/خامة')),
            ],
            options={
                'verbose_name': 'سطر تخطيط مادة',
                'verbose_name_plural': 'سطور تخطيط المواد',
                'ordering': ('material__name',),
            },
        ),
        migrations.CreateModel(
            name='MaterialPlanning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, unique=True, verbose_name='كود التخطيط')),
                ('planned_quantity', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='الكمية المخطط لها')),
                ('uom_code', models.CharField(blank=True, default='', max_length=16, verbose_name='وحدة القياس (رمز)')),
                ('required_date', models.DateField(verbose_name='تاريخ الحاجة')),
                ('warehouse', models.CharField(blank=True, default='', max_length=64, verbose_name='المخزن/الموقع')),
                ('planning_type', models.CharField(choices=[('MRP', 'تخطيط احتياجات المواد'), ('MPS', 'جدولة الإنتاج الرئيسي'), ('MANUAL', 'يدوي')], default='MRP', max_length=10, verbose_name='نوع التخطيط')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('CONFIRMED', 'مؤكد'), ('RUNNING', 'قيد التشغيل'), ('COMPLETED', 'مكتمل'), ('CANCELLED', 'ملغى'), ('LOCKED', 'مغلق')], db_index=True, default='DRAFT', max_length=12, verbose_name='الحالة')),
                ('priority', models.PositiveSmallIntegerField(default=2, verbose_name='الأولوية')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('demand_source', models.CharField(choices=[('MANUAL', 'مدخل يدويًا'), ('SO', 'أمر بيع'), ('FC', 'تنبؤ'), ('PRJ', 'مشروع')], default='MANUAL', max_length=8, verbose_name='مصدر الطلب')),
                ('demand_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='مرجع المصدر')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='مولّد تلقائيًا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plans', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تخطيط مواد',
                'verbose_name_plural': 'تخطيطات المواد',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanningException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='الكود')),
                ('message', models.CharField(max_length=255, verbose_name='الرسالة')),
                ('severity', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'مرتفع'), ('CRIT', 'حرج')], default='MEDIUM', max_length=6, verbose_name='الخطورة')),
                ('resolved', models.BooleanField(default=False, verbose_name='محلول؟')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptions', to='mrp.materialline', verbose_name='سطر')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='mrp.materialplanning', verbose_name='تخطيط')),
            ],
            options={
                'verbose_name': 'استثناء تخطيط',
                'verbose_name_plural': 'استثناءات التخطيط',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='materialline',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mrp.materialplanning', verbose_name='تخطيط'),
        ),
        migrations.CreateModel(
            name='ProcurementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('BUY', 'شراء'), ('MAKE', 'تصنيع'), ('TRANSFER', 'تحويل مخزني')], db_index=True, max_length=10, verbose_name='نوع الاقتراح')),
                ('suggested_qty', models.DecimalField(decimal_places=3, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='الكمية المقترحة')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('target_warehouse', models.CharField(blank=True, default='', max_length=64, verbose_name='المخزن الهدف')),
                ('vendor_hint', models.CharField(blank=True, default='', max_length=128, verbose_name='مورد مُقترح (اختياري)')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('APPROVED', 'معتمد'), ('REJECTED', 'مرفوض'), ('EXECUTED', 'تم التنفيذ'), ('CANCELLED', 'ملغى')], default='DRAFT', max_length=12, verbose_name='حالة الاقتراح')),
                ('auto_generated', models.BooleanField(default=True, verbose_name='مولَّد تلقائيًا')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='mrp.materialline', verbose_name='سطر التخطيط')),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaserequest', verbose_name='طلب شراء')),
            ],
            options={
                'verbose_name': 'اقتراح توريد/تصنيع',
                'verbose_name_plural': 'اقتراحات التوريد/التصنيع',
                'ordering': ('status', 'due_date'),
                'indexes': [models.Index(fields=['status', 'due_date'], name='mrp_procure_status_4e4a2e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='materialplanning',
            index=models.Index(fields=['status', 'required_date'], name='mrp_materia_status_a83586_idx'),
        ),
        migrations.AddIndex(
            model_name='materialplanning',
            index=models.Index(fields=['product', 'required_date'], name='mrp_materia_product_ecac82_idx'),
        ),
        migrations.AddIndex(
            model_name='materialline',
            index=models.Index(fields=['material'], name='mrp_materia_materia_437fa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialline',
            constraint=models.UniqueConstraint(fields=('planning', 'material'), name='uq_mrp_line_planning_material'),
        ),
    ]
