# Generated by Django 4.2.7 on 2025-08-10 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_type', models.CharField(choices=[('operational', 'تشغيلي'), ('financial', 'مالي'), ('supply', 'سلاسل التوريد'), ('legal', 'قانوني'), ('other', 'أخرى')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], max_length=20)),
                ('probability', models.IntegerField(help_text='احتمالية حدوث الخطر (1-100)')),
                ('mitigation_plan', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
