# Generated by Django 4.2.7 on 2025-08-10 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('weekly', 'جرد جزئي أسبوعي'), ('monthly', 'جرد شهري'), ('annual', 'جرد سنوي')], max_length=20, verbose_name='نوع الجرد')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'جرد فعلي',
                'verbose_name_plural': 'جرد فعلي',
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='كمية النظام')),
                ('physical_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية الفعلية')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الفرق')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'تفاصيل الجرد',
                'verbose_name_plural': 'تفاصيل الجرد',
            },
        ),
        migrations.CreateModel(
            name='InventoryDiscrepancyInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('action_taken', models.TextField(blank=True, null=True, verbose_name='الإجراء المتخذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تحقيق في فروقات الجرد',
                'verbose_name_plural': 'تحقيقات فروقات الجرد',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit', models.CharField(choices=[('pcs', 'قطعة'), ('kg', 'كيلو'), ('m', 'متر'), ('roll', 'رول'), ('box', 'علبة')], default='pcs', max_length=10, verbose_name='وحدة القياس')),
                ('min_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'عنصر مخزون',
                'verbose_name_plural': 'عناصر المخزون',
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('unit', models.CharField(choices=[('pcs', 'قطعة'), ('kg', 'كيلو'), ('m', 'متر'), ('roll', 'رول'), ('box', 'علبة')], default='kg', max_length=20, verbose_name='وحدة القياس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'مادة خام',
                'verbose_name_plural': 'المواد الخام',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المخزن')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='المدير')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'دخول'), ('out', 'خروج'), ('adjust', 'تسوية')], max_length=10, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='العنصر')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-date'],
            },
        ),
    ]
