# Generated by Django 4.2.7 on 2025-08-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='inventorydiscrepancyinvestigation',
            name='audit_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryaudititem', verbose_name='عنصر الجرد'),
        ),
        migrations.AddField(
            model_name='inventorydiscrepancyinvestigation',
            name='reported_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancy_reports', to=settings.AUTH_USER_MODEL, verbose_name='تم التبليغ إلى'),
        ),
        migrations.AddField(
            model_name='inventoryaudititem',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryaudit', verbose_name='الجرد'),
        ),
        migrations.AddField(
            model_name='inventoryaudititem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.finishedproduct', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='inventoryaudit',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('product', 'warehouse')},
        ),
    ]
