# Generated by Django 4.2.7 on 2025-08-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصميم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='patterns/images/', verbose_name='صورة')),
                ('gerber_file', models.FileField(blank=True, null=True, upload_to='patterns/gerber/', verbose_name='ملف Gerber')),
                ('pattern_type', models.CharField(choices=[('basic', 'أساسي'), ('print', 'طباعة'), ('embroidery', 'تطريز'), ('laser', 'قص ليزر')], default='basic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatternPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القطعة')),
                ('fabric_type', models.CharField(max_length=100, verbose_name='نوع القماش')),
                ('length_cm', models.FloatField(verbose_name='الطول (سم)')),
                ('width_cm', models.FloatField(verbose_name='العرض (سم)')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='pattern.patterndesign')),
            ],
        ),
        migrations.CreateModel(
            name='PatternExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('operator_name', models.CharField(max_length=100, verbose_name='اسم منفذ الباترون')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern.patterndesign')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executed_patterns', to='production.productionorder')),
            ],
        ),
    ]
