# Generated by Django 4.2.7 on 2025-08-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('operational', 'تعمل'), ('stopped', 'متوقفة'), ('maintenance', 'صيانة')], default='operational', max_length=20)),
                ('total_runtime_hours', models.PositiveIntegerField(default=0)),
                ('production_line', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(verbose_name='وصف المشكلة')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوضة'), ('in_progress', 'جاري التنفيذ'), ('completed', 'تمت الصيانة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات التنفيذ')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.machine', verbose_name='الماكينة')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='المبلغ')),
            ],
            options={
                'verbose_name': 'طلب صيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('maintenance_date', models.DateField()),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('issue', models.TextField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='maintenance.machine')),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
