# Generated by Django 4.2.7 on 2025-08-19 18:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='وسيلة التواصل')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='DistributionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('product_name', models.CharField(max_length=100, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('Confirmed', 'تم التأكيد'), ('Dispatched', 'تم الإرسال'), ('Delivered', 'تم التسليم'), ('Cancelled', 'ملغي')], default='Pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'طلب توزيع',
                'verbose_name_plural': 'طلبات التوزيع',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='رقم التتبع')),
                ('shipped_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الشحن')),
                ('status', models.CharField(choices=[('In Transit', 'قيد الشحن'), ('Delivered', 'تم التسليم'), ('Returned', 'مرتجع'), ('Lost', 'مفقود'), ('Delayed', 'متأخر')], default='In Transit', max_length=20, verbose_name='حالة الشحنة')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='آخر موقع معروف')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='ملاحظات التسليم')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.distributionorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['-shipped_date'],
            },
        ),
    ]
