# Generated by Django 4.2.7 on 2025-08-19 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('type', models.CharField(choices=[('خصم', 'خصم'), ('مكافأة', 'مكافأة'), ('إنذار', 'إنذار')], max_length=50, verbose_name='نوع الإجراء')),
                ('value_type', models.CharField(choices=[('مبلغ', 'مبلغ'), ('نسبة', 'نسبة')], default='مبلغ', max_length=10, verbose_name='نوع القيمة')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='القيمة')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('created_by', models.CharField(max_length=100, verbose_name='تم بواسطة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('related_month', models.CharField(blank=True, max_length=7, null=True, verbose_name='الشهر المرتبط')),
                ('is_approved', models.BooleanField(default=True, verbose_name='معتمد؟')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل إجراء تأديبي',
                'verbose_name_plural': 'السجلات التأديبية',
                'ordering': ['-date'],
            },
        ),
    ]
