# Generated by Django 4.2.7 on 2025-08-10 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200, verbose_name='المنتج')),
                ('quantity_missing', models.IntegerField(verbose_name='الكمية المفقودة')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف النشاط المشبوه')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشاط')),
                ('resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='RiskIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Stock', 'مخزون'), ('Finance', 'مالية'), ('Sales', 'مبيعات'), ('System', 'نظام')], max_length=50, verbose_name='فئة الحدث')),
                ('event_type', models.CharField(max_length=100, verbose_name='نوع الحدث')),
                ('risk_level', models.CharField(choices=[('LOW', 'منخفض'), ('MEDIUM', 'متوسط'), ('HIGH', 'مرتفع')], max_length=10, verbose_name='مستوى المخاطر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='الإجراء أو البلاغ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل؟')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحل')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('warning', 'إنذار'), ('suspension', 'إيقاف'), ('deduction', 'خصم'), ('termination', 'فصل')], max_length=20, verbose_name='نوع الإجراء')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taken', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
