# Generated by Django 4.2.7 on 2025-08-19 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('tracking_code', models.CharField(max_length=100, unique=True, verbose_name='كود التتبع')),
                ('customer_name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('vodafone', 'فودافون كاش'), ('instapay', 'إنستا باي'), ('bank', 'تحويل بنكي')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'قيد الشحن'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'أُلغيت')], default='pending', max_length=20, verbose_name='حالة الشحنة')),
                ('shipping_company', models.CharField(blank=True, max_length=100, verbose_name='شركة الشحن')),
                ('shipment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الشحن')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تتبع شحنة',
                'verbose_name_plural': 'تتبع الشحنات',
            },
        ),
        migrations.CreateModel(
            name='ProductTrackingMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='الموقع الحالي')),
                ('status', models.CharField(choices=[('pending', 'قيد الشحن'), ('in_transit', 'قيد النقل'), ('delivered', 'تم التسليم'), ('cancelled', 'أُلغيت')], max_length=20, verbose_name='الحالة')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحركة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='tracking.producttracking', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'حركة شحنة',
                'verbose_name_plural': 'حركات الشحنات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
