# Generated by Django 4.2.7 on 2025-08-10 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('company', 'شركة'), ('person', 'فرد')], default='person', max_length=20, verbose_name='النوع')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='الرقم الضريبي')),
                ('accounting_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='كود الحساب المحاسبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='آخر نشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
                'indexes': [models.Index(fields=['name'], name='partners__name_idx'), models.Index(fields=['phone'], name='partners__phone_idx'), models.Index(fields=['email'], name='partners__email_idx')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('new', 'عميل جديد'), ('regular', 'عميل منتظم'), ('vip', 'عميل VIP')], default='new', max_length=10, verbose_name='نوع العميل')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='النقاط')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المشتريات')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='آخر عملية شراء')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='صورة العميل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='clients.partner', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'عميل (بروفايل)',
                'verbose_name_plural': 'عملاء (بروفايل)',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'فاتورة'), ('shipping', 'شحن'), ('other', 'أخرى')], default='billing', max_length=20, verbose_name='نوع العنوان')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='الشارع')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرمز البريدي')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.partner', verbose_name='الشريك')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.customer',),
        ),
    ]
