# Generated by Django 4.2.7 on 2025-08-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surveychoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='surveychoice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='surveychoice',
            name='text',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='order',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='الإجابة النصية'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='التقييم (إن وجد)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.surveychoice', verbose_name='الاختيار المحدد'),
        ),
        migrations.AddField(
            model_name='surveychoice',
            name='choice_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='الاختيار'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='question_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نص السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyresponse', verbose_name='الاستجابة'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الاستبيان'),
        ),
        migrations.AlterField(
            model_name='surveychoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.surveyquestion', verbose_name='السؤال'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'نص'), ('multiple_choice', 'اختيار من متعدد'), ('rating', 'تقييم رقمي')], max_length=20, verbose_name='نوع السؤال'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='الاستبيان'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجابة'),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='الاستبيان'),
        ),
    ]
