# Generated by Django 4.2.7 on 2025-08-10 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', max_length=1)),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('total_rewards', models.PositiveIntegerField(default=0)),
                ('total_deductions', models.PositiveIntegerField(default=0)),
                ('total_warnings', models.PositiveIntegerField(default=0)),
                ('total_evaluations', models.PositiveIntegerField(default=0)),
                ('evaluation_score', models.FloatField(default=0.0)),
                ('behavior_status', models.CharField(default='جيد', max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_excused_absence', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_attendance_records', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('commitment_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quarterly_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_monthly_incentives', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
